name: DEMO CI/CD

on: [push]

jobs:
  Build_AND_Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Configs
      run: |
           git config user.email "${{ secrets.GITHUB_EMAIL }}"
           git config user.name "${{ secrets.GITHUB_USERNAME }}"
           git config --global credential.helper wincred
           git remote set-url https://${{ secrets.GITHUB_USERNAME }}:${{ secrets.GITHUB_PASS }}@github.com/${{ secrets.GITHUB_USERNAME }}/<repo_name>.git
    - name: Compile
      run: npm install
    - name: Create Deploy Bundle
      run: npm run build
    - name: Deploy
      run: npm run deploy