name: DEMO CI/CD

on: [push]

jobs:
  Build_AND_Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Configs
      run: |
           git config --global user.email "${{ secrets.GITHUB_EMAIL }}"
           git config --global user.name "${{ secrets.GITHUB_USERNAME }}"
           git remote set-url origin https://{{ secrets.GITHUB_GH_PAGES_TOKEN }}@github.com/${{ secrets.GITHUB_USERNAME }}/react-redux-realworld-example-app.git
    - name: Compile
      run: npm install
    - name: Create Deploy Bundle
      run: npm run build
    - name: Deploy
      run: |
           npm run deploy
           cat /home/runner/.npm/_logs/2020-02-12T04_47_56_268Z-debug.log