name: DEMO CI/CD

on: [push]

jobs:
  Compile And Build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Install npm
      run: npm install
    - name: Create Deploy Bundle
      run: npm run build
  
  Deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Deploy
      run: npm run deploy