name: DEMO CI/CD

on: [push]

jobs:
  Build_AND_Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Configs
      run: |
           git config user.email "$GITHUB_EMAIL"
           git config user.name "$GITHUB_USERNAME"
    - name: Compile
      run: npm install
    - name: Create Deploy Bundle
      run: npm run build
    - name: Deploy
      run: npm run deploy