name: DEMO CI/CD

on: [push]

jobs:
  Build_AND_Deploy:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set Configs
      run: |
           git config user.email "${{ secrets.GITHUB_EMAIL }}"
           git config user.name "${{ secrets.GITHUB_USERNAME }}"
           git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
    - name: Compile
      run: npm install
    - name: Create Deploy Bundle
      run: npm run build
    - name: Deploy
      run: npm run deploy